apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev

resources:
- configmap.yaml
- ./../../base

# If you have any patches to apply to the base resources, you can specify them here.
# patches:
#   - path: deployment-patch.yml
#     target:
#       kind: Deployment

images:
- name: deployment-image
  newName: quangmanhlam/user-bff-dev
  newTag: cfad5c4e4014c7ba9c8ed36b497250e6e2126811
