apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: opa-dev

resources:
  - ../../../base/opa

patches:
  - path: policy-configmap.yaml
    target:
      kind: ConfigMap
      name: opa-policy
  - path: deployment.yaml
    target:
      kind: Deployment
      name: opa-deployment
