apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: demo-applicationset
  namespace: argocd
spec:
  generators:
    - matrix:
        generators:
          - list:
              elements:
                - app: user-fe
                - app: user-be
                - app: user-bff
          - list:
              elements:
                - env: dev
                # - env: test
                # - env: stage
  template:
    metadata:
      # This will create names like dev, test, stage
      name: '{{env}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/lamquangmanh/gitops-config.git
        targetRevision: main
        # This points to the folder in your Git repo (e.g., microk8s/microservice/apps/user-fe/overlays/dev)
        path: microk8s/microservice/apps/{{app}}/overlays/{{env}}
      destination:
        server: https://kubernetes.default.svc
        # Dynamic namespace, e.g., dev, test, stage
        namespace: '{{env}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
