apiVersion: extauth.solo.io/v1alpha1
kind: ExtAuthConfig
metadata:
  name: opa-auth-config
  namespace: gloo-gateway-dev
spec:
  glooAuth:
    configs:
      - opaAuth:
          request:
            http:
              uri: http://opa.opa-dev.svc.cluster.local:8181/v1/data/authz/allow
              method: POST
