apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- deployment.yaml
- service.yaml
- hpa.yaml
- sealed-secrets.yaml
images:
- name: deployment-image
  newName: quangmanhlam/user-be-dev
  newTag: c18670312902f96b53be027dc9199d89277e626e
