apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev

resources:
- ./../../base
- configmap.yaml
- ingress.yaml
  # - secrets.yaml

# If you have any patches to apply to the base resources, you can specify them here.
# patches:
#   - path: deployment-patch.yml
#     target:
#       kind: Deployment

images:
- name: deployment-image
  newName: quangmanhlam/user-fe-dev
  newTag: 7a40fec2fc9bf3b91ec63ce16d7d86fb91d87dcb
