apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev

resources:
- ./../../base
- configmap.yaml
- ingress.yaml
  # - secrets.yaml

# If you have any patches to apply to the base resources, you can specify them here.
# patches:
#   - path: deployment-patch.yml
#     target:
#       kind: Deployment

images:
- name: deployment-image
  newName: quangmanhlam/user-fe-dev
  newTag: 6f76b96e9e17fae223d89fee2c4bf39da9a12317
