resources:
  - ../../../../base/backend-applicationset.yaml

patches:
  - target:
      kind: ApplicationSet
      name: backend-applications
    patch: |-
      - op: replace
        path: /spec/generators/0/list/elements/0/cluster
        value: cluster: https://35.229.211.176
