gatewayProxies:
  gatewayProxy:
    service:
      # type: NodePort: Exposes the service on the node’s IP at a static port (useful for Minikube or bare-metal).
      type: NodePort
      # httpPort: 32080: HTTP traffic will be available on port 32080.
      httpPort: 31848
      # httpsPort: 32443: HTTPS traffic will be available on port 32443.
      httpsPort: 32400

gloo:
  gateway:
    validation:
      # Skips strict validation of gateway resources (like routes).
      # Allows Gloo to accept resources even if they're not 100% correct — useful for local testing, not recommended in production.
      alwaysAcceptResources: true
    proxyServiceAccount:
      # Tells Helm to create a Kubernetes ServiceAccount for the gateway proxy.
      # This is required so the gateway proxy can authenticate and access cluster resources properly.
      create: true

    # Enables REST-based Endpoint Discovery Service (EDS).
    # This is an internal optimization for how Gloo communicates service discovery info to Envoy (the proxy).
    enableRestEds: true

settings:
  # Creates the Settings CRD instance needed by Gloo to store global configuration.
  # Without this, Gloo will not function properly.
  create: true

extauth:
  # Enables the external authentication service (e.g., API keys, JWT validation, OPA, etc.).
  enabled: true
  # Allows matching and applying authentication to part of a route, not the whole path. Useful for fine-grained access control.
  allowPartialRouteMatch: true
