apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgres-exporter
spec:
  chart:
    spec:
      chart: postgresql-exporter
      version: 3.0.0
      sourceRef:
        kind: HelmRepository
        name: bitnami
  values:
    postgresUser: myuser
    postgresPassword: mypassword
    datasource:
      url: 'postgresql://postgres:azQwSxEdcrfVgtb@postgresql-service.default.svc.cluster.local:5432/postgres'
