apiVersion: v1
kind: Service
metadata:
  namespace: backend-dev
  name: demo-be-svc
  labels:
    app: demo-be-svc-label
spec:
  ports:
    - name: http
      port: 3000 # External port within the cluster
      targetPort: 3000 # The port your container is listening on
    - name: grpc
      port: 5000 # External port within the cluster
      targetPort: 5000 # The port your container is listening on
  selector:
    app: demo-be-label
  # To expose the service externally (Optional):
  # For LoadBalancer (e.g., on cloud environments like GCP, AWS):
  # type: LoadBalancer

  # For NodePort (e.g., for local Kubernetes setups like Minikube):
  # type: NodePort

  # Default type, can be changed to NodePort or LoadBalancer
  # type: ClusterIP
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   namespace: backend-dev
#   name: auth-be-svc
#   labels:
#     app: auth-be-svc-label
# spec:
#   ports:
#     - name: http
#       port: 3000 # External port within the cluster
#       targetPort: 3000 # The port your container is listening on
#   selector:
#     app: demo-be-label
