apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps-of-infrastructure
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/lamquangmanh/gitops-config.git
    targetRevision: HEAD
    path: microk8s/infrastructure/apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps-of-microservice
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/lamquangmanh/gitops-config.git
    targetRevision: HEAD
    path: microk8s/microservice/applicationset
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/lamquangmanh/gitops-config.git
    targetRevision: main
    path: microk8s/monitoring
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: promtail
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: promtail
    targetRevision: 6.15.3 # or latest
    helm:
      values: |
        config:
          clients:
            - url: http://loki.monitoring.svc.cluster.local:3100/loki/api/v1/push
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka-ui
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/lamquangmanh/gitops-config.git
    targetRevision: HEAD
    path: microk8s/infrastructure/installation/kafka-ui
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

---
# # monitoring/minio/application.yaml
# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: minio
#   namespace: argocd
# spec:
#   project: default
#   source:
#     repoURL: 'https://charts.min.io/' # Helm chart repository
#     targetRevision: '5.4.0'
#     chart: minio
#     helm:
#       values: |-
#         accessKey: minioadmin
#         secretKey: minioadmin123
#         persistence:
#           enabled: true
#           size: 256Gi
#           storageClass: standard
#         service:
#           type: ClusterIP
#         console:
#           enabled: true
#         ingress:
#           enabled: true
#           ingressClassName: traefik
#           annotations:
#             kubernetes.io/ingress.class: traefik
#           hosts:
#             - minio.manhlam.name.vn
#           tls:
#             - secretName: minio-tls
#               hosts:
#                 - minio.manhlam.name.vn
#   destination:
#     server: https://kubernetes.default.svc
#     namespace: minio
#   syncPolicy:
#     automated:
#       prune: true
#       selfHeal: true
#     syncOptions:
#       - CreateNamespace=true
