# apiVersion: helm.toolkit.fluxcd.io/v2beta1
# kind: HelmRelease
# metadata:
#   name: grafana
#   namespace: monitoring
# spec:
#   interval: 5m
#   chart:
#     spec:
#       chart: grafana
#       version: 6.61.0
#       sourceRef:
#         kind: HelmRepository
#         name: grafana
#         namespace: monitoring
#   values:
#     grafana:
#       enabled: true
#       adminPassword: 'admin123456'
#       service:
#         type: ClusterIP
#       ingress:
#         enabled: true
#         annotations:
#           nginx.ingress.kubernetes.io/rewrite-target: /
#           kubernetes.io/ingress.class: nginx
#         path: /
#         pathType: Prefix
#         hosts:
#           - grafana.manhlam.name.vn
#     persistence:
#       enabled: true
#       size: 10Gi
#     datasources:
#       datasources.yaml:
#         apiVersion: 1
#         datasources:
#           - name: Loki
#             type: loki
#             url: http://loki.monitoring.svc.cluster.local:3100
#           - name: Tempo
#             type: tempo
#             url: http://tempo.monitoring.svc.cluster.local:3100

apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: grafana
      version: 6.61.0
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: monitoring
  values:
    adminPassword: 'admin123456'
    service:
      type: ClusterIP

    ingress:
      enabled: true
      annotations:
        nginx.ingress.kubernetes.io/rewrite-target: /
        kubernetes.io/ingress.class: nginx
      path: /
      pathType: Prefix
      hosts:
        - grafana.manhlam.name.vn

    persistence:
      enabled: true
      size: 10Gi

    datasources:
      datasources.yaml:
        apiVersion: 1
        datasources:
          - name: Loki
            type: loki
            access: proxy
            url: http://10.1.41.183:3100
            # url: http://loki.monitoring.svc.cluster.local:3100
          - name: Tempo
            type: tempo
            access: proxy
            url: http://tempo.monitoring.svc.cluster.local:3100
          - name: Prometheus
            type: prometheus
            url: http://prometheus-kube-prometheus-prometheus.monitoring.svc.cluster.local:9090
    sidecar:
      dashboards:
        enabled: true
        label: grafana_dashboard
        searchNamespace: ALL
    dashboards:
      default:
        prometheus:
          gnetId: 2
          revision: 2
          datasource: Prometheus
        redis:
          gnetId: 11835
          revision: 1
          datasource: Prometheus
        postgresql:
          gnetId: 9628
          revision: 1
          datasource: Prometheus

        # Kubernetes Cluster Monitoring
        kubernetes-cluster:
          gnetId: 315
          revision: 3
          datasource: Prometheus

        # Kubernetes Nodes
        kubernetes-nodes:
          gnetId: 1860
          revision: 21
          datasource: Prometheus

        # Kubernetes Pods
        kubernetes-pods:
          gnetId: 8563
          revision: 1
          datasource: Prometheus

        # Kubelet / Node Exporter (if installed)
        node-exporter-full:
          gnetId: 1860
          revision: 21
          datasource: Prometheus
