apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: demo-applicationset
  namespace: argocd
spec:
  generators:
    - matrix:
        generators:
          - list:
              elements:
                - app: frontend
                  repoURL: https://github.com/lamquangmanh/demo-fe.git
                - app: backend
                  repoURL: https://github.com/lamquangmanh/demo-be.git
          - list:
              elements:
                - env: dev
                # - env: test
                # - env: stage
  template:
    metadata:
      # This will create names like frontend-dev, backend-prod
      name: '{{app}}-{{env}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/lamquangmanh/gitops-config.git
        targetRevision: main
        # This points to the folder in your Git repo (e.g., k3s-apps/overlays/frontend/dev)
        path: k3s-apps/overlays/{{app}}/{{env}}
      destination:
        server: https://kubernetes.default.svc
        # Dynamic namespace, e.g., frontend-dev, backend-prod
        namespace: '{{app}}-{{env}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
