---
apiVersion: v1
kind: Service
metadata:
  name: redis-external
  namespace: dev
spec:
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
---
apiVersion: v1
kind: Endpoints
metadata:
  name: redis-external
  namespace: dev
subsets:
  - addresses:
      - ip: 192.168.1.40
    ports:
      - port: 6379
