apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: traefik-ingress-dev

resources:
  - ../../../base/traefik-ingress

patches:
  - path: ingress.yaml
    target:
      kind: Ingress
      name: ingress-dev
  - path: middleware-opa.yaml
    target:
      kind: Middleware
      name: opa-auth
