apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: user-fe-dev
  name: user-fe-deployment
  labels:
    app: user-fe-deployment-label
spec:
  replicas: 1
  # The revisionHistoryLimit field in your Deployment manifest controls how many old ReplicaSets Kubernetes should retain for rollback purposes.
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: user-fe-deployment-label
  template:
    metadata:
      labels:
        app: user-fe-deployment-label
    spec:
      containers:
        - name: user-fe
          image: deployment-image
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: '64m' # Minimum CPU requested (200 millicores)
              memory: '128Mi' # Minimum memory requested (256 MiB)
            limits:
              cpu: '2' # Maximum CPU allowed (1024 millicores = 1 CPU)
              memory: '1Gi' # Maximum memory allowed (1 GiB)
