apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
  # - secrets.yaml
resources:
- namespace.yaml
- deployment.yaml
- service.yaml
- hpa.yaml
- configmap.yml
images:
- name: deployment-image
  newName: quangmanhlam/user-fe-dev
  newTag: d8de693f9be27815e85581e9ca3148dcefc40c2a
