apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- deployment.yaml
- service.yaml
- hpa.yaml
images:
- name: deployment-image
  newName: quangmanhlam/user-fe-dev
  newTag: fcc235d25142101b6f1aa77358bc9906070bc139
