apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
  # - hpa.yaml
resources:
- namespace.yaml
- deployment.yaml
- service.yaml
- secrets.yaml
    # - configmap.yml
images:
- name: deployment-image
  newName: quangmanhlam/user-fe-dev
  newTag: d333f66d30c64911193ee14e1c6ddf5b59035a71
