apiVersion: v1
kind: Service
metadata:
  namespace: user-fe-dev
  name: user-fe-svc
  labels:
    app: user-fe-svc-label
spec:
  ports:
    - port: 3000 # External port within the cluster
      targetPort: 3000 # The port your container is listening on
      # nodePort: 30080 # Explicitly specify the NodePort to access externally
  selector:
    app: user-fe-deployment-label

  # To expose the service externally (Optional):
  # For LoadBalancer (e.g., on cloud environments like GCP, AWS):
  # type: LoadBalancer

  # For NodePort (e.g., for local Kubernetes setups like Minikube):
  # type: NodePort

  # Default type, can be changed to NodePort or LoadBalancer
  # type: ClusterIP
