apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev

resources:
  - configmap.yaml
  - postgres-external-service.yml
  - redis-external-service.yml
  - ./../../base

# If you have any patches to apply to the base resources, you can specify them here.
# patches:
#   - path: deployment-patch.yml
#     target:
#       kind: Deployment

images:
  - name: deployment-image
    newName: quangmanhlam/user-backend-dev
    newTag: 1f2b6230226fbfc2d3670ad243bc2101beffcb40
