apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev

resources:
- configmap.yaml
- postgres-external-service.yml
- redis-external-service.yml
- ./../../base

# If you have any patches to apply to the base resources, you can specify them here.
# patches:
#   - path: deployment-patch.yml
#     target:
#       kind: Deployment

images:
- name: deployment-image
  newName: quangmanhlam/user-backend-dev
  newTag: 7508a34e012c5ba98d82b7aee4b178354f93487f
