apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus
  namespace: monitoring
spec:
  install:
    crds: CreateReplace
  chart:
    spec:
      chart: kube-prometheus-stack
      version: 56.6.0
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: monitoring
  interval: 10m
  values:
    prometheus:
      prometheusSpec:
        # Crucial: Set this to false to ensure empty selectors mean "select all"
        # and don't get overridden by Helm's default release labels.
        serviceMonitorSelectorNilUsesHelmValues: false
        serviceMonitorSelector: {}
        # If redis-exporter was in a different namespace, you'd configure it here.
        # Since it's in the same 'monitoring' namespace, an empty selector here
        # will select ServiceMonitors within its own namespace.
        serviceMonitorNamespaceSelector: {}
