# Bỏ hạn chế user (chạy bằng root để mở port 80/443)
podSecurityContext: {}
securityContext: {}

# Cấu hình các entry points: HTTP, HTTPS, dashboard
entryPoints:
  web:
    address: ':80'
  websecure:
    address: ':443'
  traefik:
    address: ':9020'

# Bật dashboard qua CRD
ingressRoute:
  dashboard:
    enabled: true

# Expose service bằng LoadBalancer (hoặc NodePort nếu bạn không dùng cloud)
service:
  type: LoadBalancer
  ports:
    web:
      port: 80
      targetPort: web
    websecure:
      port: 443
      targetPort: websecure
    traefik:
      port: 9020
      targetPort: traefik
      name: traefik

# Bật Prometheus metrics
metrics:
  prometheus:
    enabled: true

# Bật ping để kiểm tra health
ping:
  enabled: true

# Bật log debug để theo dõi nếu lỗi
logs:
  general:
    level: DEBUG

# Bật healthcheck nếu dùng readinessProbe / livenessProbe
healthcheck:
  enabled: true
