apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: backend-dev
  name: demo-be
  labels:
    app: demo-be-label
spec:
  replicas: 1
  # The revisionHistoryLimit field in your Deployment manifest controls how many old ReplicaSets Kubernetes should retain for rollback purposes.
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: demo-be-label
  template:
    metadata:
      labels:
        app: demo-be-label
    spec:
      containers:
        - name: demo-be
          image: deployment-image
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
            - name: grpc
              containerPort: 5000
              protocol: TCP
          envFrom:
            - secretRef:
                name: backend-dev-sealed-secret
          resources:
            requests:
              cpu: '64m' # Minimum CPU requested (200 millicores)
              memory: '128Mi' # Minimum memory requested (256 MiB)
            limits:
              cpu: '256m' # Maximum CPU allowed (500 millicores)
              memory: '512Mi' # Maximum memory allowed (512 MiB)
