apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- account.yaml
- deployment.yaml
- service.yaml
- hpa.yaml
images:
- name: deployment-image
  newName: quangmanhlam/demo-fe
  newTag: 4113e8dde7f6564187c0e6301c9a8dd179457ae1
