apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgres-exporter
  namespace: monitoring
spec:
  chart:
    spec:
      chart: postgresql-exporter
      version: 3.1.2
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: monitoring
  values:
    serviceMonitor:
      enabled: true
    config:
      datasource:
        host: 192.168.1.10
        port: 5432
        user: postgres
        password: azQwSxEdcrfVgtb
        database: postgres
    #   extendQueryPath: /etc/queries.yaml
    # extraSecretMounts:
    #   - name: custom-queries
    #     mountPath: /etc
    #     secretName: pg-custom-queries
