apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: redis-exporter
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: prometheus-redis-exporter
      version: 6.12.0
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: monitoring
  values:
    redisAddress: redis://192.168.1.10:6379
    redisPassword: zaqwsxcdeRFVvFrTgb
    serviceMonitor:
      enabled: true
# apiVersion: helm.toolkit.fluxcd.io/v2beta1
# kind: HelmRelease
# metadata:
#   name: redis-exporter
#   namespace: monitoring
# spec:
#   interval: 5m
#   chart:
#     spec:
#       chart: prometheus-redis-exporter
#       version: 5.6.0 # or any valid version from the repo
#       sourceRef:
#         kind: HelmRepository
#         name: prometheus-community
#         namespace: monitoring
#   values:
#     redisAddress: redis://192.168.1.10:6379
#     redisPassword: zaqwsxcdeRFVvFrTgb
#     serviceMonitor:
#       enabled: true
# ---------
# apiVersion: helm.toolkit.fluxcd.io/v2beta1
# kind: HelmRelease
# metadata:
#   name: redis
#   namespace: monitoring
# spec:
#   chart:
#     spec:
#       chart: redis-exporter
#       sourceRef:
#         kind: HelmRepository
#         name: prometheus-community
#         namespace: monitoring
#   interval: 5m
#   values:
#     serviceMonitor:
#       enabled: true
#     redisAddress: 'redis://192.168.1.10:6379'
#     redisPassword: 'zaqwsxcdeRFVvFrTgb'
