apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: user-bff-dev
  name: user-bff-dev-deployment
  labels:
    app: user-bff-dev-label
spec:
  replicas: 1
  # The revisionHistoryLimit field in your Deployment manifest controls how many old ReplicaSets Kubernetes should retain for rollback purposes.
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: user-bff-dev-label
  template:
    metadata:
      labels:
        app: user-bff-dev-label
    spec:
      # hostNetwork: true # Use host networking for the pod to connect postgres and redis
      # dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: user-bff
          image: deployment-image
          ports:
            - name: http
              containerPort: 4000
              protocol: TCP
          envFrom:
            - secretRef:
                name: user-bff-dev-secret
          resources:
            requests:
              cpu: '512m' # Minimum CPU requested (200 millicores)
              memory: '1Gi' # Minimum memory requested (256 MiB)
            limits:
              cpu: '4' # Maximum CPU allowed (1024 millicores = 1 CPU)
              memory: '2Gi' # Maximum memory allowed (2 GB)
