apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: user-be-hpa
  namespace: user-bff-dev
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: user-bff-dev-deployment
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        # Specifies that the HPA should monitor CPU usage.
        name: cpu
        target:
          type: Utilization
          # The target is 80% CPU utilization across all pods.
          averageUtilization: 80
    - type: Resource
      resource:
        # Specifies that the HPA should monitor memory usage
        name: memory
        target:
          type: Utilization
          # The target is 80% memory utilization across all pods.
          averageUtilization: 80
