apiVersion: v1
kind: Service
metadata:
  namespace: user-bff-dev
  name: user-bff-svc
  labels:
    app: user-bff-svc-label
spec:
  ports:
    - name: http
      port: 4000 # External port within the cluster
      targetPort: 4000 # The port your container is listening on
  selector:
    app: user-bff-dev-deployment
  type: ClusterIP # Expose the service internally within the cluster
