apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tempo
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: tempo
      version: 1.8.0
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: monitoring
  values:
    serviceMonitor:
      enabled: true
    tempo:
      metricsGenerator:
        enabled: true
    traces:
      otlp:
        http:
          enabled: true
        grpc:
          enabled: true
