apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: frontend-applications
spec:
  generators:
    - list:
        elements:
          - env: dev
            cluster: https://35.229.211.176
            branchName: dev
          # - env: test
          #   cluster: https://gke-test.example.com
          # - env: stag
          #   cluster: https://gke-stag.example.com
  template:
    metadata:
      name: 'frontend-{{env}}'
    spec:
      # Specifies which ArgoCD project this application belongs to. By default, it belongs to the demo project.
      project: demo
      source:
        repoURL: https://github.com/lamquangmanh/demo-fe.git
        # This specifies the Git branch or tag that ArgoCD will track. In this case, it's tracking the {branchName} branch.
        targetRevision: '{{branchName}}'
        path: overlays/{{env}}
      destination:
        server: '{{cluster}}'
        namespace: '{{env}}'
      syncPolicy:
        # This enables automatic synchronization of the application.
        # When the application configuration is updated, ArgoCD will automatically apply the changes
        automated:
          # This ensures that any resources (e.g., Pods, Deployments) that are no longer part of the application are deleted automatically.
          prune: true
          # This ensures that if any resources drift from the desired state, ArgoCD will automatically bring them back into the correct state.
          selfHeal: true
