apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: frontend-dev
  name: hello-app
  labels:
    app: hello-app-label
spec:
  replicas: 2
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: hello-app-label
  template:
    metadata:
      labels:
        app: hello-app-label
    spec:
      containers:
        - name: hello-app
          image: gcr.io/google-samples/hello-app:1.0
          ports:
            - containerPort: 8080
