version: '3.8'
services:
  temporal-db:
    image: postgres:15
    environment:
      - POSTGRES_USER=temporal
      - POSTGRES_PASSWORD=temporal
      - POSTGRES_DB=temporal
    ports:
      - '15432:5432'
    volumes:
      - temporal_pgdata:/var/lib/postgresql/data

  temporal:
    image: temporalio/auto-setup:1.21.1
    environment:
      - DB=postgresql
      - DB_HOST=temporal-db
      - DB_PORT=5432
      - DB_USER=temporal
      - DB_PWD=temporal
      - DB_NAME=temporal
    depends_on:
      - temporal-db

  temporal-web:
    image: temporalio/ui:latest
    ports:
      - '8088:8080'
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
    depends_on:
      - temporal

  # Optional: Prometheus and Grafana for monitoring. we'll explore this on prometheus and grafana in kubernetes setup
  # prometheus:
  #   image: prom/prometheus:latest
  #   container_name: prometheus
  #   ports:
  #     - '9095:9090' # Prometheus UI → đổi từ 9090 sang 9095
  #   volumes:
  #     - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro

  # grafana:
  #   image: grafana/grafana:latest
  #   container_name: grafana
  #   ports:
  #     - '8086:8085' # Grafana → đổi từ 8085 sang 8086

volumes:
  temporal_pgdata:
