version: '3.8'

services:
  temporal-db:
    image: postgres:15
    container_name: temporal-db
    environment:
      POSTGRES_USER: temporal
      POSTGRES_PASSWORD: temporal
      POSTGRES_DB: temporal
    ports:
      - '15432:5432'
    volumes:
      - temporal-db-data:/var/lib/postgresql/data

  temporal:
    image: temporalio/auto-setup:1.21.1
    container_name: temporal
    depends_on:
      - temporal-db
    environment:
      DB: postgresql
      DB_PORT: 5432
      POSTGRES_USER: temporal
      POSTGRES_PWD: temporal
      POSTGRES_SEEDS: temporal-db
      DYNAMIC_CONFIG_FILE_PATH: config/dynamicconfig/development.yaml
    ports:
      - '7233:7233' # Temporal Frontend service

  temporal-web:
    image: temporalio/ui:latest
    container_name: temporal-web
    depends_on:
      - temporal
    environment:
      TEMPORAL_ADDRESS: temporal:7233
      TEMPORAL_CORS_ORIGINS: http://localhost:8088
    ports:
      - '8088:8080' # Web UI

volumes:
  temporal-db-data:
