ports:
  web:
    port: 80
    expose: {}
  websecure:
    port: 443
    expose: {}
  traefik:
    port: 9020
    expose: {}

entryPoints:
  web:
    address: ':80'
  websecure:
    address: ':443'
  traefik:
    address: ':9020'

ping:
  enabled: true

ingressRoute:
  dashboard:
    enabled: true

service:
  type: LoadBalancer
  ports:
    web:
      port: 80
      targetPort: web
    websecure:
      port: 443
      targetPort: websecure
    traefik:
      port: 9020
      targetPort: traefik
      name: traefik

metrics:
  prometheus:
    enabled: true

logs:
  general:
    level: DEBUG

healthcheck:
  enabled: true
